// Confluences
var table ctFeaturesTable = table.new(position.bottom_right, 1, 10, border_width=1, border_color=tableBorderColor, frame_width = 1, frame_color=tableBorderColor)
var ctSupportResistanceFeature = false
var ctTrendLineFeature = false
var ctMovingAverageFeature = false
var ctDivergencesFeature = false
var ctBreakAndRetestFeature = false
var ctCandlebarPatternFeature = false
if barstate.islastconfirmedhistory
    table.cell(ctFeaturesTable, 0, 0, "Confluences", bgcolor=tableHeaderColor, text_color=color.white)
    table.cell(ctFeaturesTable, 0, 1, "Support/Resistance", bgcolor=ctSupportResistanceFeature ? tableSuccessColor : tableValueColor, text_color=color.white)
    table.cell(ctFeaturesTable, 0, 2, "Trend Line", bgcolor=ctTrendLineFeature ? tableSuccessColor : tableValueColor, text_color=color.white)
    table.cell(ctFeaturesTable, 0, 3, "Moving Average", bgcolor=ctMovingAverageFeature ? tableSuccessColor : tableValueColor, text_color=color.white)
    table.cell(ctFeaturesTable, 0, 4, "Divergences", bgcolor=ctDivergencesFeature ? tableSuccessColor : tableValueColor, text_color=color.white)
    table.cell(ctFeaturesTable, 0, 5, "Break & Retest", bgcolor=ctBreakAndRetestFeature ? tableSuccessColor : tableValueColor, text_color=color.white) 
    table.cell(ctFeaturesTable, 0, 6, "Candlebar patterns", bgcolor=ctCandlebarPatternFeature ? tableSuccessColor : tableValueColor, text_color=color.white)