// Ema
var emaFeatureName = "Ema"
emaEnabled = input.bool(true, "Enabled", group=emaFeatureName)
emaLength = input.int(600, "Lenght", minval=1, group=emaFeatureName)
emaColor = input.color(color.yellow, "Color", group=emaFeatureName)
ema = ta.ema(close, emaLength)
emaBullish = close > ema
emaBearish = close < ema
plot(ema, color=emaColor, linewidth = 2, display=emaEnabled ? display.all : display.none)