// Rsi divergencies
rdLength = input.int(14, "RSI Length", minval=1)
rdLoopBackLength = input.int(50, "Loop back Length")
rdHighestPoint = high == ta.highest(high, rdLoopBackLength)
rdLowestPoint = low == ta.lowest(low, rdLoopBackLength)
rdRsi = ta.rsi(close, rdLength)
rdDelayedRsi = rdRsi[4]
rdRsiHighest = ta.highest(rdDelayedRsi, rdLoopBackLength)
rdRsiLowest = ta.lowest(rdDelayedRsi, rdLoopBackLength)
rdHasHigherRsi = rdRsi < rdRsiHighest
rdHasLowerRsi = rdRsi > rdRsiLowest
rdBullDivergence = rdLowestPoint and rdHasLowerRsi
rdBearDivergence = rdHighestPoint and rdHasHigherRsi
plotshape(rdBullDivergence, style=shape.triangleup, location=location.belowbar, color=color.green, size=size.normal, title="Bull Divergence")
plotshape(rdBearDivergence, style=shape.triangledown, location=location.abovebar, color=color.red, size=size.normal, title="Bear Divergence")