//SuperTrend
stEnabled = input.bool(false, "Enabled", group="SuperTrend Settings")
stPeriod = input.int(10, "Length", group="SuperTrend Settings")
stFactor = input.float(4.0, "Factor", step = 0.01, group="SuperTrend Settings")
stBullColor = input.color(color.green, "Bull color", group="SuperTrend Settings")
stBearColor = input.color(color.red, "Bear color", group="SuperTrend Settings")
[st, stDirection] = ta.supertrend(stFactor, stPeriod)
stDescending = stDirection >= 0
stAscending = stDirection < 0
stMiddleTrend = plot((open + close) / 2, display=display.none)
stUpTrend = plot(stDirection < 0 ? st : na, "Up Trend", color = stBullColor, style=plot.style_linebr, display=stEnabled ? display.all : display.none)
stDownTrend = plot(stDirection < 0? na : st, "Down Trend", color = stBearColor, style=plot.style_linebr, display=stEnabled ? display.all : display.none)
fill(stMiddleTrend, stUpTrend, color = color.new(stBullColor, 90), fillgaps=false, display=stEnabled ? display.all : display.none)
fill(stMiddleTrend, stDownTrend, color = color.new(stBearColor, 90), fillgaps=false, display=stEnabled ? display.all : display.none)