// Tips
var ttBorderColor = color.white
var ttHeaderColor = color.blue
var ttValueColor = color.black
var table ttTable = table.new(position.top_right, 1, 10, border_width=1, border_color=ttBorderColor, frame_width = 1, frame_color=ttBorderColor)
if barstate.islastconfirmedhistory
    table.cell(ttTable, 0, 0, "Tips", bgcolor=ttHeaderColor, text_color=color.white)
    table.cell(ttTable, 0, 1, "Enfocarse en el 'PROCESO', no en el 'RESULTADO'", bgcolor=ttValueColor, text_color=color.white)
    table.cell(ttTable, 0, 2, "Evitar trades de VENGANZA", bgcolor=ttValueColor, text_color=color.white)